#version: '3.8'  # Use version 3.8 or later

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 4g
    restart: unless-stopped
    stdin_open: true  # Equivalent to -it for interactive terminal
    tty: true  # Allocate a pseudo-TTY
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data  # Optional: Persistent storage

# volumes:
#   esdata:
#     driver: local
